# Generated by Django 3.2.6 on 2021-08-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_ordermodel_is_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='myfile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
