# Generated by Django 3.2.6 on 2021-08-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_ordermodel_myfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
