# Generated by Django 3.2.6 on 2021-08-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_ordermodel_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='myfile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
