# Generated by Django 3.2.6 on 2021-08-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_ordermodel_myfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='myfile',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
