# Generated by Django 3.2.6 on 2021-08-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_ordermodel_myfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='myfile',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='upload',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
