# Generated by Django 3.2.6 on 2021-08-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20210829_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
